name: Python Code Formatting Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - dev

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the appropriate Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run Black and Auto-Fix Formatting
        run: |
          black .

      - name: Commit and Push Changes (if needed)
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Auto-format code with Black" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
