name: Merge Test to Dev and Delete Test Branch

on:
  push:
    branches:
      - test

jobs:
  merge-and-delete:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0  # Fetch full history to ensure proper merging

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Merge Test into Dev
        run: |
          git checkout dev
          git pull origin dev
          git merge --no-ff test -m "Auto-merge test into dev"
          git push origin dev

      - name: Delete Test Branch
        run: |
          git push origin --delete test
