name: Python Code Formatting Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - dev

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the appropriate Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Check code formatting with black
        run: |
          black --check .

      - name: Fail if code is not formatted
        run: |
          if ! black --check .; then
            echo "Code is not formatted correctly with black"
            exit 1
          fi
