name: Sync Dev to Main

on:
  push:
    branches:
      - dev

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dev Branch
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Push Changes to Main
        run: |
          git checkout main
          git merge --no-ff dev -m "Auto-merge dev into main"
          git push origin main

